---
version: "3.9"
services:
  # Init container
  init:
    build:
      context: .
    image: "django_cms_k8s_demo"
    container_name: "django_cms_init"
    command: "sh -c 'python manage.py collectstatic --noinput --clear && python manage.py migrate --noinput'"
    volumes:
      - "./:/app"
    env_file:
      - .env-local
    depends_on:
      mysql:
        condition: service_healthy

  # Wagtail container
  web:
    image: "django_cms_k8s_demo"
    container_name: "django_cms_web"
    ports:
      - "127.0.0.1:8000:8000"
    command: "sh -c 'python manage.py runserver 0.0.0.0:8000'"
    volumes:
      - "./:/app"
    env_file:
      - .env-local
    depends_on:
      init:
        condition: service_completed_successfully
      mysql:
        condition: service_healthy

  # MySQL container
  mysql:
    container_name: "mysql_k8s_demo"
    image: "mysql/mysql-server:8.0.28"
    env_file:
      - .env-local
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
